/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficos;

import Logica.Bloque;

import Logica.Amplitud;
import java.awt.GridLayout;
import Recursos.IcoRecurso;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauro
 */
public class UsuarioVisual extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioVisual
     */
   
    ArrayList<Bloque> objetivos;
    public Bloque[][] matrix;
    public Bloque[][] matrixGrafico;
    Bloque init = new Bloque();

    public UsuarioVisual() {
        initComponents();
        //Funcines para el Inicio del Mapa
        this.objetivos = new ArrayList<>();
//        this.matrix = lectura.ReadFile();
//      this.objetivos = (ArrayList<Bloque>) lectura.getObjetivos().clone();
//       init = lectura.init;
        this.creacionBotones(matrix);
        this.repaint();
        this.setSize(550, 520);
        //setResizable(false);
    }

    //Diseñada para generar los iconos
    private ImageIcon IconoMapa(Bloque bloque) {
        ImageIcon imagen = new ImageIcon();
        //Poner condicionales para elementos graficos
        if (bloque.getContenido() == -1) {
            imagen = IcoRecurso.ICON_MARCA;
        }
        if (bloque.getContenido() == 1) {
            //PASTO
            imagen = IcoRecurso.ICON_MURO;
        }
        if (bloque.getContenido() == 2) {
            imagen = IcoRecurso.ICON_ROBOT;
        }
        if (bloque.getContenido() == 3) {
            //FLOR
            imagen = IcoRecurso.ICON_TRAJE;
        }
        if (bloque.getContenido() == 4) {
            //CABALLO BLANCO
            imagen = IcoRecurso.ICON_RAYOAZUL;
        }
        if (bloque.getContenido() == 5) {
            //CABALLO NEGRO
            imagen = IcoRecurso.ICON_RAYOROJO;
        }
        if (bloque.getContenido() == 6) {
            imagen = IcoRecurso.ICON_BATERIA;
        }
        return imagen;
    }

    /*Funcion diseñada para llenar el JPmapa de Botones*/
    public void creacionBotones(Bloque[][] matrix) {

        //this.setSize(450, 492);
        jPmapa.removeAll();
        int filas = 8;
        int columnas = 8;
        jPmapa.setLayout(new GridLayout(8, 8));
        
        //*
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                JButton boton= new JButton();
                boton.setIcon(IconoMapa(matrix[j][i]));
                jPmapa.add(boton);
                if((matrix[j][i].getContenido() == 5) || (matrix[j][i].getContenido() == 6)){
                    
                    boton.setEnabled(false);
                    
                }
                
                
                //*
            }
        }
        jPmapa.updateUI();
        jPmapa.revalidate();
        jPmapa.repaint();
        
    }
    

    void printmatrix(Bloque[][] matrix) {
        System.out.println("Pintando Matriz");
        for (int i = 0; i < matrix.length; i++) {
            //Filas
            for (int j = 0; j < matrix.length; j++) {
                System.out.print(" " + matrix[j][i].getContenido() + " |");
            }
            System.out.println("-");
        }

    }

    private void MostrarCamino(ArrayList<Bloque> entrada) {
        /*Esta funcion Pinta el camino probeniente de los algoritmos de busqueda*/
        Bloque[][] mapa = new Bloque[8][8];
        mapa = matrix.clone();
        for (int i = 0; i < entrada.size(); i++) {
            try {
                mapa[entrada.get(i).getUbicacion().x][entrada.get(i).getUbicacion().y].setContenido(2);
                creacionBotones(mapa);
                Thread.sleep(800);
                printmatrix(mapa);
                creacionBotones(mapa);
                mapa[entrada.get(i).getUbicacion().x][entrada.get(i).getUbicacion().y].setContenido(-1);
            } catch (InterruptedException ex) {
                JOptionPane.showMessageDialog(this, "Error en Tiempo de espera del Hilo de Ejecucion");
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jBbuscar = new javax.swing.JButton();
        jPBanner = new javax.swing.JPanel();
        jPmapa = new javax.swing.JPanel();
        jLTitle = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jBbuscar.setBackground(new java.awt.Color(255, 255, 255));
        jBbuscar.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jBbuscar.setText("Empezar el juego");
        jBbuscar.setContentAreaFilled(false);
        jBbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jPBanner.setBackground(new java.awt.Color(204, 255, 204));

        jPmapa.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPmapaLayout = new javax.swing.GroupLayout(jPmapa);
        jPmapa.setLayout(jPmapaLayout);
        jPmapaLayout.setHorizontalGroup(
            jPmapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPmapaLayout.setVerticalGroup(
            jPmapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );

        jLTitle.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLTitle.setForeground(new java.awt.Color(0, 0, 153));
        jLTitle.setText("Hungry horses 1.0");

        javax.swing.GroupLayout jPBannerLayout = new javax.swing.GroupLayout(jPBanner);
        jPBanner.setLayout(jPBannerLayout);
        jPBannerLayout.setHorizontalGroup(
            jPBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBannerLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLTitle)
                .addContainerGap(326, Short.MAX_VALUE))
            .addGroup(jPBannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPmapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBannerLayout.setVerticalGroup(
            jPBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBannerLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLTitle)
                .addGap(17, 17, 17)
                .addComponent(jPmapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBbuscar)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jBbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
         System.out.println("Tamaño matrix "+matrix[0].length );
      
           Amplitud amplitud = new Amplitud("Principiante");
            ArrayList<Bloque> s = new ArrayList<>();
            s = amplitud.minimax(init);
            HiloGrafico hilo = new HiloGrafico(s, this);
            hilo.execute();
       
            
    }//GEN-LAST:event_jBbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscar;
    private javax.swing.JLabel jLTitle;
    private javax.swing.JPanel jPBanner;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPmapa;
    // End of variables declaration//GEN-END:variables

}
